APP_WIDTH = 240
APP_HEIGHT = 180

EDITOR_IMAGE_X = 0
EDITOR_IMAGE_Y = 64
EDITOR_IMAGE_WIDTH = 160
EDITOR_IMAGE_HEIGHT = 160

TILEMAP_IMAGE_X = 192
TILEMAP_IMAGE_Y = 64
TILEMAP_IMAGE_WIDTH = 64
TILEMAP_IMAGE_HEIGHT = 63

TOOL_SELECT = 0
TOOL_PENCIL = 1
TOOL_RECTB = 2
TOOL_RECT = 3
TOOL_CIRCB = 4
TOOL_CIRC = 5
TOOL_BUCKET = 6
