import os

import pyxel

WIDGET_HOLD_TIME = 16
WIDGET_REPEAT_TIME = 2
WIDGET_CLICK_TIME = 5
WIDGET_CLICK_DIST = 3
WIDGET_PANEL_COLOR = 1
WIDGET_BACKGROUND_COLOR = 7
WIDGET_SHADOW_COLOR = 13

BUTTON_ENABLED_COLOR = 12
BUTTON_DISABLED_COLOR = 5
BUTTON_PRESSED_COLOR = 7
BUTTON_TEXT_COLOR = 1
BUTTON_LIGHTING_TIME = 4

INPUT_TEXT_COLOR = 1
INPUT_FIELD_COLOR = 10

EDITOR_IMAGE_FILE = "assets/editor_220x160.png"
EDITOR_IMAGE = pyxel.Image.from_image(
    os.path.join(os.path.dirname(__file__), EDITOR_IMAGE_FILE)
)

APP_WIDTH = 240
APP_HEIGHT = 180

TILEMAP_IMAGE_X = 0
TILEMAP_IMAGE_Y = 192
TILEMAP_IMAGE_WIDTH = 64
TILEMAP_IMAGE_HEIGHT = 63

TOOL_SELECT = 0
TOOL_PENCIL = 1
TOOL_RECTB = 2
TOOL_RECT = 3
TOOL_CIRCB = 4
TOOL_CIRC = 5
TOOL_BUCKET = 6

MAX_SOUND_LENGTH = 48
MAX_MUSIC_LENGTH = 32

TEXT_LABEL_COLOR = 7
HELP_MESSAGE_COLOR = 5

PANEL_FOCUS_COLOR = 7
PANEL_FOCUS_BORDER_COLOR = 0
PANEL_SELECT_FRAME_COLOR = 15
PANEL_SELECT_BORDER_COLOR = 0

PIANO_KEYBOARD_REST_COLOR = 12
PIANO_KEYBOARD_PLAY_COLOR = 14

PIANO_ROLL_CURSOR_PLAY_COLOR = 14
PIANO_ROLL_CURSOR_EDIT_COLOR = 6
PIANO_ROLL_BACKGROUND_COLOR = 7
PIANO_ROLL_NOTE_COLOR = 8
PIANO_ROLL_REST_COLOR = 5

OCTAVE_BAR_BACKGROUND_COLOR = 7
OCTAVE_BAR_COLOR = 13

SOUND_FIELD_DATA_NORMAL_COLOR = 1
SOUND_FIELD_DATA_FOCUS_COLOR = 7
SOUND_FIELD_FOCUS_COLOR = 1

MUSIC_FIELD_BACKGROUND_COLOR = 6
MUSIC_FIELD_CURSOR_PLAY_COLOR = 8
MUSIC_FIELD_CURSOR_EDIT_COLOR = 1
MUSIC_FIELD_SOUND_NORMAL_COLOR = 1
MUSIC_FIELD_SOUND_FOCUS_COLOR = 7
