WIDGET_HOLD_TIME = 18
WIDGET_REPEAT_TIME = 3
WIDGET_CLICK_TIME = 10
WIDGET_CLICK_DIST = 3
WIDGET_FRAME_COLOR = 1
WIDGET_BACKGROUND_COLOR = 6
WIDGET_SHADOW_COLOR = 13

BUTTON_ENABLED_COLOR = 13
BUTTON_DISABLED_COLOR = 5
BUTTON_PRESSED_COLOR = 7
BUTTON_TEXT_COLOR = 1
BUTTON_LIGHTING_TIME = 4

INPUT_TEXT_COLOR = 1
INPUT_FIELD_COLOR = 9
