from pyxel import _get_constant_number

WIDGET_HOLD_TIME = 16
WIDGET_REPEAT_TIME = 2
WIDGET_CLICK_TIME = 5
WIDGET_CLICK_DIST = 3
WIDGET_PANEL_COLOR = 1
WIDGET_BACKGROUND_COLOR = 6
WIDGET_SHADOW_COLOR = 13

BUTTON_ENABLED_COLOR = 13
BUTTON_DISABLED_COLOR = 5
BUTTON_PRESSED_COLOR = 7
BUTTON_TEXT_COLOR = 1
BUTTON_LIGHTING_TIME = 4

INPUT_TEXT_COLOR = 1
INPUT_FIELD_COLOR = 9

FONT_WIDTH = _get_constant_number("FONT_WIDTH")
FONT_HEIGHT = _get_constant_number("FONT_HEIGHT")
