WIDGET_CLICK_DIST = 3
WIDGET_CLICK_TIME = 10
WIDGET_HOLD_TIME = 20
WIDGET_REPEAT_TIME = 5
WIDGET_FRAME_COLOR = 1
WIDGET_SHADOW_COLOR = 13
WIDGET_BACKGROUND_COLOR = 6

BUTTON_LIGHTING_TIME = 4
BUTTON_ENABLED_COLOR = 13
BUTTON_DISABLED_COLOR = 5
BUTTON_PRESSED_COLOR = 7
BUTTON_TEXT_COLOR = 1
