UI_BASE_COLOR = 8  # 1
UI_INPUT_COLOR = 9
UI_SHADOW_COLOR = 2  # 13
UI_BACKGROUND_COLOR = 5  # 6

WIDGET_HOLD_FRAME = 20
WIDGET_REPEAT_FRAME = 5
WIDGET_CLICK_DIST = 3
WIDGET_CLICK_FRAME = 10

BUTTON_LIGHTING_TIME = 4
BUTTON_ENABLED_COLOR = 13
BUTTON_DISABLED_COLOR = 5
BUTTON_PRESSED_COLOR = 7
BUTTON_TEXT_COLOR = 1
