import glfw

from . import core

VERSION = core.get_constant_number("VERSINO")


GIF_TRANSPARENCY_COLOR = (255, 0, 0)

MOUSE_CURSOR_IMAGE_X = 0
MOUSE_CURSOR_IMAGE_Y = 16
MOUSE_CURSOR_WIDTH = 8
MOUSE_CURSOR_HEIGHT = 8

APP_SCREEN_MAX_SIZE = 255
APP_SCREEN_SCALE_CUTDOWN = 2
APP_SCREEN_SCALE_MINIMUM = 2
APP_GIF_CAPTURE_COUNT = 900
APP_GIF_CAPTURE_SCALE = 2
APP_MEASURE_FRAME_COUNT = 10

RENDERER_IMAGE_COUNT = 4
RENDERER_IMAGE_WIDTH = 256
RENDERER_IMAGE_HEIGHT = 256
RENDERER_TILEMAP_COUNT = 8
RENDERER_TILEMAP_WIDTH = 256
RENDERER_TILEMAP_HEIGHT = 256
RENDERER_MIN_TEXTURE_SIZE = 256

DRAW_TYPE_PIX = 0
DRAW_TYPE_LINE = 1
DRAW_TYPE_RECT = 2
DRAW_TYPE_RECTB = 3
DRAW_TYPE_CIRC = 4
DRAW_TYPE_CIRCB = 5
DRAW_TYPE_BLT = 6
DRAW_TYPE_TEXT = 7
DRAW_MAX_COUNT = 10000

FONT_MIN_CODE = 32
FONT_MAX_CODE = 127
FONT_WIDTH = 4
FONT_HEIGHT = 6

AUDIO_SAMPLE_RATE = 22050
AUDIO_BLOCK_SIZE = 2205
AUDIO_CHANNEL_COUNT = 4
AUDIO_SOUND_COUNT = 65
AUDIO_MUSIC_COUNT = 8
AUDIO_ONE_SPEED = AUDIO_SAMPLE_RATE // 120
AUDIO_ONE_VOLUME = 0x7FFF // (AUDIO_CHANNEL_COUNT * 7)

SOUND_TONE_TRIANGLE = 0
SOUND_TONE_SQUARE = 1
SOUND_TONE_PULSE = 2
SOUND_TONE_NOISE = 3
SOUND_EFFECT_NONE = 0
SOUND_EFFECT_SLIDE = 1
SOUND_EFFECT_VIBRATO = 2
SOUND_EFFECT_FADEOUT = 3
SOUND_NOTE_TABLE = {"c": 0, "d": 2, "e": 4, "f": 5, "g": 7, "a": 9, "b": 11}
SOUND_TONE_TABLE = {
    "t": SOUND_TONE_TRIANGLE,
    "s": SOUND_TONE_SQUARE,
    "p": SOUND_TONE_PULSE,
    "n": SOUND_TONE_NOISE,
}
SOUND_EFFECT_TABLE = {
    "n": SOUND_EFFECT_NONE,
    "s": SOUND_EFFECT_SLIDE,
    "v": SOUND_EFFECT_VIBRATO,
    "f": SOUND_EFFECT_FADEOUT,
}
