#!/usr/bin/env python3

import re
import sys


def replace_file(file, pattern, repl):
    with open(file, "r") as f:
        code = f.read()

    code = re.sub(pattern, repl, code, 1)

    with open(file, "w") as f:
        f.write(code)


def update_version():
    if len(sys.argv) < 2:
        print("update_version VERSION")
        exit(1)

    version = sys.argv[1]

    replace_file("engine/src/settings.rs", '(VERSION.*)".*"', f'\\1"{version}"')
    replace_file("engine/Cargo.toml", '(version.*)".*"', f'\\1"{version}"')
    replace_file("wrapper/Cargo.toml", '(version.*)".*"', f'\\1"{version}"')
    replace_file("wrapper/Cargo.toml", '(engine", version.*)".*"', f'\\1"{version}"')
    replace_file("setup.iss", '(PyxelVersion.*)".*"', f'\\1"{version}"')


if __name__ == "__main__":
    update_version()
