#!/usr/bin/env python3

import os
import re
import sys

LIB_DIR = "."


def replace_file(file, pattern, repl):
    with open(os.path.join(LIB_DIR, file), "r") as f:
        code = f.read()

    code = re.sub(pattern, repl, code, 1)

    with open(file, "w") as f:
        f.write(code)


def update_version():
    if len(sys.argv) < 2:
        print("update_version VERSION")
        exit(1)

    version = sys.argv[1]
    os.chdir(os.path.dirname(os.path.abspath(__file__)))
    replace_file("engine/src/settings.rs", '(VERSION.*)".*"', f'\\1"{version}"')
    replace_file("engine/Cargo.toml", '(version.*)".*"', f'\\1"{version}"')
    replace_file("wrapper/Cargo.toml", '(version.*)".*"', f'\\1"{version}"')
    replace_file("wrapper/Cargo.toml", '(engine", version.*)".*"', f'\\1"{version}"')
    replace_file("../setup.py", '(version=.*)".*"', f'\\1"{version}"')
    replace_file("setup.iss", '(PyxelVersion.*)".*"', f'\\1"{version}"')


if __name__ == "__main__":
    update_version()
