#!/bin/sh -e

ROOT_DIR=..
PROJECTS_DIR=..
PYODIDE_DIR=$PROJECTS_DIR/pyodide
PYODIDE_REPO=https://github.com/pyodide/pyodide
SRC_DIR=$PYODIDE_DIR/dist
DST_DIR=wasm/pyodide_sdl2
FILES=(
    pyodide.js
    pyodide.js.map
    pyodide.asm.js
    pyodide.asm.wasm
    pyodide.asm.data
    pyodide_py.tar
    repodata.json
)

cd `dirname $0`/$ROOT_DIR
if [ -d $PYODIDE_DIR ]; then
    rm -rf $DST_DIR
    mkdir -p $DST_DIR
    for file in "${FILES[@]}"
    do
        cp $SRC_DIR/$file $DST_DIR
    done
else
    cd $PROJECTS_DIR
    git clone $PYODIDE_REPO
    cd -
    cd $PYODIDE_DIR
    sed -i -e "s/\\(-s MAIN_MODULE=1\\)/\\1 -s USE_SDL=2 -s GL_WORKAROUND_SAFARI_GETCONTEXT_BUG=0/" Makefile.envs
    ./run_docker
    # Then 'make' in the container
fi
