#!/bin/sh

ROOT_DIR=..
VENV=.venv

cd `dirname $0`/$ROOT_DIR
rm -rf $VENV
python3 -m venv $VENV
if [ "$COMSPEC" == "" ]; then
    source $VENV/bin/activate
else
    . $VENV/Scripts/activate
fi
pip3 install -U pip
pip3 install -r requirements.txt
