#!/usr/bin/env python3

import os
import sys

def extract_sections(input_file):
    file_name = os.path.splitext(os.path.basename(input_file))[0].replace('.', '_')
    output_file = f"sections_{file_name}.txt"
    with open(input_file, 'r', encoding='utf-8') as infile, open(output_file, 'w', encoding='utf-8') as outfile:
        for line in infile:
            if line.startswith("##"):
                outfile.write(line)

if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(1)
    input_file = sys.argv[1]
    extract_sections(input_file)
