#!/usr/bin/env python3

import io
import json
import os
import pathlib

import PIL
import requests

ROOT_DIR = ".."
PYXEL_USER_EXAMPLES_JSON = "docs/pyxel_user_examples.json"


def download_gif_frame(url, frame):
    response = requests.get(url)
    if response.status_code != 200:
        raise Exception(f"HTTP error: {response.status_code}")
    gif = PIL.Image.open(io.BytesIO(response.content))
    gif.seek(frame)
    return gif.copy()


def generate_pyxel_thanks():
    os.chdir(pathlib.Path(__file__).parent / ROOT_DIR)
    with open(PYXEL_USER_EXAMPLES_JSON, "r", encoding="utf-8") as f:
        data = json.load(f)


if __name__ == "__main__":
    generate_pyxel_thanks()
