#!/usr/bin/env python3

import os
import re
import sys

ROOT_DIR = ".."


def replace_file(file, pattern, repl):
    with open(file, "r") as f:
        code = f.read()
    code = re.sub(pattern, repl, code, 1)
    with open(file, "w") as f:
        f.write(code)


def update_version():
    if len(sys.argv) < 2:
        print("update_version VERSION")
        exit(1)
    os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), ROOT_DIR))
    version = sys.argv[1]
    replace_file(
        "crates/pyxel-core/src/settings.rs", '(VERSION.*)".*"', f'\\1"{version}"'
    )
    replace_file("pyproject.toml", '(version.*)".*"', f'\\1"{version}"')
    replace_file("crates/pyxel-core/Cargo.toml", '(version.*)".*"', f'\\1"{version}"')
    replace_file(
        "crates/pyxel-extension/Cargo.toml", '(version.*)".*"', f'\\1"{version}"'
    )
    replace_file(
        "crates/pyxel-extension/Cargo.toml",
        '(pyxel-core", version.*)".*"',
        f'\\1"{version}"',
    )
    replace_file("wasm/pyxel.js", "(PYXEL_WHEEL.*?)-.*?-", f"\\1-{version}-")


if __name__ == "__main__":
    update_version()
