#!/bin/bash

set -e
cd `dirname $0`

VENV_DIR=../venv
REQUIREMENTS=../requirements.txt

rm -rf $VENV_DIR
python3 -m venv $VENV_DIR
. $VENV_DIR/*/activate
python3 -m pip install -U pip
pip3 install -r $REQUIREMENTS
