#!/bin/sh -e

ROOT_DIR=..
VENV_DIR=venv

if [ "$COMSPEC" == "" ]; then
    PYTHON=python3
    PIP=pip3
else # Windows
    PYTHON=python
    PIP=pip
fi

cd `dirname $0`/$ROOT_DIR
rm -rf $VENV_DIR
$PYTHON -m venv $VENV_DIR
source $VENV_DIR/*/activate
$PYTHON -m pip install -U pip
$PIP install -r requirements.txt
