#!/bin/bash

set -eu
cd `dirname $0`

INDEX_HTML=../index.html
EXAMPLES_DIR=../wasm/examples
TEST_REGEX="src=\\\"https:.*/pyxel.js\\\""
REPLACE_REGEX="src=\\\".*/pyxel.js\\\""
RELPATH_SRC1="src=\\\"wasm/pyxel.js\\\""
RELPATH_SRC2="src=\\\"../pyxel.js\\\""
ABSPATH_SRC="src=\\\"https://cdn.jsdelivr.net/gh/kitao/pyxel/wasm/pyxel.js\\\""

if grep "$TEST_REGEX" $INDEX_HTML > /dev/null; then
    sed -i -e "s#$REPLACE_REGEX#$RELPATH_SRC1#" $INDEX_HTML
    find $EXAMPLES_DIR/*.html | xargs sed -i -e "s#$REPLACE_REGEX#$RELPATH_SRC2#"
else
    sed -i -e "s#$REPLACE_REGEX#$ABSPATH_SRC#" $INDEX_HTML
    find $EXAMPLES_DIR/*.html | xargs sed -i -e "s#$REPLACE_REGEX#$ABSPATH_SRC#"
fi
rm -f $INDEX_HTML-e
rm -f $EXAMPLES_DIR/*.html-e
