#!/bin/bash

set -e
cd `dirname $0`

LAUNCHER_HTML=../wasm/launcher/index.html
EXAMPLES_DIR=../wasm/examples
WHEEL_VERSION=`find ../wasm/*.whl | sed "s/.*pyxel-\([^-]*\)-.*/\1/"`
SRC_REGEX="src=\\\".*/pyxel.js\\\""
LOCAL_SRC="src=\\\"../pyxel.js\\\""
CDN_SRC="src=\\\"https://cdn.jsdelivr.net/gh/kitao/pyxel@v$WHEEL_VERSION/wasm/pyxel.js\\\""

if [ "$1" == "local" ]; then
    sed -i -e "s#$SRC_REGEX#$LOCAL_SRC#" $LAUNCHER_HTML
    find $EXAMPLES_DIR/*.html | xargs sed -i -e "s#$SRC_REGEX#$LOCAL_SRC#"
elif [ "$1" == "cdn" ]; then
    sed -i -e "s#$SRC_REGEX#$CDN_SRC#" $LAUNCHER_HTML
    find $EXAMPLES_DIR/*.html | xargs sed -i -e "s#$SRC_REGEX#$CDN_SRC#"
else
    echo "switch_html_scripts local_or_cdn"
    exit 0
fi
rm -f $LAUNCHER_HTML-e
rm -f $EXAMPLES_DIR/*.html-e
