extend = "../Makefile.toml"

[tasks.format]
alias = "cargo-format"

[tasks.clean]
alias = "cargo-clean"

[tasks.build]
alias = "cargo-build"

[tasks.build-release]
alias = "cargo-build-release"

[tasks.test]
dependencies = ["cargo-build", "cargo-test"]
