#!/usr/bin/env python3

import os
import pathlib
import re
from urllib.parse import urljoin

ROOT_DIR = ".."
RELPATH_README = "README.md"
ABSPATH_README = "docs/README-abspath.md"


def generate_readme_abspath():
    os.chdir(pathlib.Path(__file__).parent / ROOT_DIR)

    relpath_dir = os.path.dirname(RELPATH_README)
    relpath_dir = (relpath_dir.rstrip("/") + "/") if relpath_dir else ""

    blob_prefix = urljoin("https://github.com/kitao/pyxel/blob/main/", relpath_dir)
    raw_prefix = urljoin(
        "https://raw.githubusercontent.com/kitao/pyxel/main/", relpath_dir
    )

    with open(RELPATH_README, "r", encoding="utf-8") as fh:
        text = fh.read()
        text = re.sub(
            r'(\]\(|href=")(?!http)',
            r"\1" + blob_prefix,
            text,
        )
        text = re.sub(
            r'(src=")',
            r"\1" + raw_prefix,
            text,
        )

    with open(ABSPATH_README, "w", encoding="utf-8") as fh:
        fh.write(text)


if __name__ == "__main__":
    generate_readme_abspath()
