#!/usr/bin/env python3

import pathlib
import re
from urllib.parse import urljoin

ROOT_DIR = pathlib.Path(__file__).resolve().parent.parent
SOURCE_README = ROOT_DIR / "README.md"
ABS_LINKS_README = ROOT_DIR / "docs/README-abs-links.md"


def generate_readme_abs_links():
    source_rel_dir = SOURCE_README.relative_to(ROOT_DIR).parent.as_posix()
    relpath_dir = "" if source_rel_dir == "." else f"{source_rel_dir}/"

    blob_prefix = urljoin("https://github.com/kitao/pyxel/blob/main/", relpath_dir)
    raw_prefix = urljoin(
        "https://raw.githubusercontent.com/kitao/pyxel/main/", relpath_dir
    )

    with SOURCE_README.open("r", encoding="utf-8") as fh:
        text = fh.read()
        text = re.sub(
            r'(\]\(|href=")(?!https?://|mailto:|#)',
            r"\1" + blob_prefix,
            text,
        )
        text = re.sub(
            r'(src=")(?!https?://|data:)',
            r"\1" + raw_prefix,
            text,
        )

    with ABS_LINKS_README.open("w", encoding="utf-8") as fh:
        fh.write(text)


if __name__ == "__main__":
    generate_readme_abs_links()
