from typing import Iterator, overload

from pyxel import Font, Image, Tilemap


# Vec3 class
class Vec3:
    x: float
    y: float
    z: float

    ZERO: Vec3
    ONE: Vec3
    RIGHT: Vec3
    LEFT: Vec3
    UP: Vec3
    DOWN: Vec3
    FORWARD: Vec3
    BACK: Vec3

    def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0) -> None: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __getitem__(self, key: int) -> float: ...
    def __iter__(self) -> Iterator[float]: ...
    def __len__(self) -> int: ...
    def __add__(self, other: Vec3) -> Vec3: ...
    def __sub__(self, other: Vec3) -> Vec3: ...
    def __mul__(self, scalar: float) -> Vec3: ...
    def __rmul__(self, scalar: float) -> Vec3: ...
    def __truediv__(self, scalar: float) -> Vec3: ...
    def __neg__(self) -> Vec3: ...
    def dot(self, other: Vec3) -> float: ...
    def cross(self, other: Vec3) -> Vec3: ...
    def length(self) -> float: ...
    def length_squared(self) -> float: ...
    def distance_to(self, other: Vec3) -> float: ...
    def distance_squared_to(self, other: Vec3) -> float: ...
    def angle_to(self, other: Vec3) -> float: ...
    def normalize(self) -> Vec3: ...
    def clamp_length(self, max_length: float) -> Vec3: ...
    def min(self, other: Vec3) -> Vec3: ...
    def max(self, other: Vec3) -> Vec3: ...
    def lerp(self, other: Vec3, t: float) -> Vec3: ...
    def slerp(self, other: Vec3, t: float) -> Vec3: ...
    def reflect(self, normal: Vec3) -> Vec3: ...
    def project(self, other: Vec3) -> Vec3: ...
    def to_local(self, mat: Mat4) -> Vec3: ...
    def to_world(self, mat: Mat4) -> Vec3: ...
    def to_local_dir(self, mat: Mat4) -> Vec3: ...
    def to_world_dir(self, mat: Mat4) -> Vec3: ...

# Mat4 class
class Mat4:
    IDENTITY: Mat4

    pos: Vec3
    rot: Vec3
    scale: Vec3

    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __getitem__(self, key: tuple[int, int]) -> float: ...
    @overload
    def __mul__(self, other: Mat4) -> Mat4: ...
    @overload
    def __mul__(self, other: Vec3) -> Vec3: ...
    @staticmethod
    def from_translation(pos: Vec3) -> Mat4: ...
    @staticmethod
    def from_rotation(rot: Vec3) -> Mat4: ...
    @staticmethod
    def from_quat(quat: Quat) -> Mat4: ...
    @staticmethod
    def from_scale(scale: Vec3) -> Mat4: ...
    @staticmethod
    def compose(pos: Vec3, rot: Vec3, scale: Vec3) -> Mat4: ...
    @staticmethod
    def look_at(eye: Vec3, target: Vec3, up: Vec3 = Vec3.UP) -> Mat4: ...
    def translate(self, v: Vec3) -> Mat4: ...
    def rotate(self, axis: Vec3, deg: float) -> Mat4: ...
    def rotate_x(self, deg: float) -> Mat4: ...
    def rotate_y(self, deg: float) -> Mat4: ...
    def rotate_z(self, deg: float) -> Mat4: ...
    def scale_by(self, v: Vec3) -> Mat4: ...
    def inverse(self) -> Mat4: ...
    def transpose(self) -> Mat4: ...
    def determinant(self) -> float: ...
    def to_local(self, mat: Mat4) -> Mat4: ...
    def to_world(self, mat: Mat4) -> Mat4: ...
    def to_local_dir(self, mat: Mat4) -> Mat4: ...
    def to_world_dir(self, mat: Mat4) -> Mat4: ...

# Quat class
class Quat:
    IDENTITY: Quat

    x: float
    y: float
    z: float
    w: float

    def __init__(
        self,
        x: float = 0.0,
        y: float = 0.0,
        z: float = 0.0,
        w: float = 1.0,
    ) -> None: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __getitem__(self, key: int) -> float: ...
    def __iter__(self) -> Iterator[float]: ...
    def __len__(self) -> int: ...
    def __neg__(self) -> Quat: ...
    @overload
    def __mul__(self, other: Quat) -> Quat: ...
    @overload
    def __mul__(self, other: Vec3) -> Vec3: ...
    @staticmethod
    def from_axis_angle(axis: Vec3, deg: float) -> Quat: ...
    @staticmethod
    def from_euler(rot: Vec3) -> Quat: ...
    @staticmethod
    def from_two_vectors(a: Vec3, b: Vec3) -> Quat: ...
    @staticmethod
    def from_matrix(mat: Mat4) -> Quat: ...
    def conjugate(self) -> Quat: ...
    def inverse(self) -> Quat: ...
    def normalize(self) -> Quat: ...
    def length(self) -> float: ...
    def length_squared(self) -> float: ...
    def dot(self, other: Quat) -> float: ...
    def angle_to(self, other: Quat) -> float: ...
    def to_matrix(self) -> Mat4: ...
    def to_euler(self) -> Vec3: ...
    def to_axis_angle(self) -> tuple[Vec3, float]: ...
    def slerp(self, other: Quat, t: float) -> Quat: ...

# Camera class
class Camera:
    transform: Mat4
    fov: float
    near: float
    far: float
    ortho_size: float | None

    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...

# ColorRamp class
class ColorRamp:
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...
    def __getitem__(self, key: tuple[int, int]) -> tuple[int, int, int]: ...
    def __setitem__(
        self, key: tuple[int, int], value: tuple[int, int, int]
    ) -> None: ...
    def build(self) -> None: ...

# Light class
class Light:
    ambient: float
    direction: Vec3
    intensity: float

    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...

# Contact class
class Contact:
    point: Vec3
    normal: Vec3

    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...

# Collider class
class Collider:
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...

# FloatBuffer class
class FloatBuffer:
    @property
    def size(self) -> int: ...

    def __init__(self, source: int | list[float] = 0) -> None: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...

    @overload
    def __getitem__(self, i: int) -> float: ...
    @overload
    def __getitem__(self, s: slice) -> list[float]: ...

    @overload
    def __setitem__(self, i: int, value: float) -> None: ...
    @overload
    def __setitem__(self, s: slice, values: list[float]) -> None: ...
    @overload
    def __setitem__(self, s: slice, values: FloatBuffer) -> None: ...

    def __iter__(self) -> Iterator[float]: ...
    def __len__(self) -> int: ...

    def fill(self, value: float) -> None: ...
    def resize(self, size: int) -> None: ...

# IntBuffer class
class IntBuffer:
    @property
    def size(self) -> int: ...

    def __init__(self, source: int | list[int] = 0) -> None: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...

    @overload
    def __getitem__(self, i: int) -> int: ...
    @overload
    def __getitem__(self, s: slice) -> list[int]: ...

    @overload
    def __setitem__(self, i: int, value: int) -> None: ...
    @overload
    def __setitem__(self, s: slice, values: list[int]) -> None: ...
    @overload
    def __setitem__(self, s: slice, values: IntBuffer) -> None: ...

    def __iter__(self) -> Iterator[int]: ...
    def __len__(self) -> int: ...

    def fill(self, value: int) -> None: ...
    def resize(self, size: int) -> None: ...

# Mesh class
class Mesh:
    col: int             # default face color (used when image is None)
    image: Image | None  # texture (None falls back to col)

    @staticmethod
    def from_vertices(
        vertices: list[Vec3],
        faces: list[tuple[int, int, int]],
        uvs: list[tuple[float, float]] | None = None,
        col: int = 7,
        image: Image | None = None,
    ) -> Mesh: ...
    @staticmethod
    def box(size: Vec3, col: int = 7) -> Mesh: ...
    @staticmethod
    def sphere(radius: float, segments: int = 16, col: int = 7) -> Mesh: ...
    @staticmethod
    def cylinder(
        radius: float, height: float, segments: int = 16, col: int = 7
    ) -> Mesh: ...
    @staticmethod
    def plane(w: float, h: float, col: int = 7) -> Mesh: ...

    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...

    @property
    def vertex_count(self) -> int: ...
    @property
    def face_count(self) -> int: ...

    # Per-element access (mutable)
    def get_vertex(self, i: int) -> Vec3: ...
    def set_vertex(self, i: int, v: Vec3) -> None: ...
    def get_uv(self, i: int) -> tuple[float, float]: ...
    def set_uv(self, i: int, uv: tuple[float, float]) -> None: ...
    def get_face(self, i: int) -> tuple[int, int, int]: ...
    def set_face(self, i: int, f: tuple[int, int, int]) -> None: ...

    # Resize (overhead-tolerant; matches Image's resize semantics)
    def resize(self, vertex_count: int, face_count: int) -> None: ...

    # Instantiate a single Node backed by this mesh
    def create_node(self) -> Node: ...

# Model class
class Model:
    @staticmethod
    def load(filename: str) -> Model: ...

    def __repr__(self) -> str: ...

    def create_node(self) -> Node: ...   # instantiate the Node tree

# Node class
class Node:
    name: str                     # tag for find(); set by Model.load for parts
    transform: Mat4
    active: bool                  # parent-dominant; False halts update + collision
    visible: bool                 # parent-dominant; False halts drawing
    collider: Collider | None
    light: Light | None           # None inherits from the closest non-None ancestor
    color_ramp: ColorRamp | None  # None inherits from the closest non-None ancestor

    @property
    def parent(self) -> Node | None: ...
    @property
    def children(self) -> tuple[Node, ...]: ...
    @property
    def camera(self) -> Camera: ...   # valid only inside on_draw

    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...

    def world_transform(self) -> Mat4: ...
    def find(self, name: str) -> Node | None: ...   # subtree DFS by name

    def add_child(self, node: Node) -> None: ...
    def remove_child(self, node: Node) -> None: ...
    def destroy(self) -> None: ...

    # Draw state (on_draw scope; resets per call)
    def pal(self, src_col: int | None = None, dst_col: int | None = None) -> None: ...
    def dither(self, alpha: float) -> None: ...
    def depth_test(self, enabled: bool) -> None: ...
    def depth_write(self, enabled: bool) -> None: ...

    # Immediate-mode draw commands (node-local coordinates)
    def pset(self, pos: Vec3, col: int) -> None: ...
    def line(self, p1: Vec3, p2: Vec3, col: int) -> None: ...
    def tri(self, p1: Vec3, p2: Vec3, p3: Vec3, col: int) -> None: ...
    def trib(self, p1: Vec3, p2: Vec3, p3: Vec3, col: int) -> None: ...
    def circ(self, pos: Vec3, r: float, col: int) -> None: ...
    def circb(self, pos: Vec3, r: float, col: int) -> None: ...
    def text(self, pos: Vec3, s: str, col: int, font: Font | None = None) -> None: ...
    def rect(self, mat: Mat4, w: float, h: float, col: int) -> None: ...
    def rectb(self, mat: Mat4, w: float, h: float, col: int) -> None: ...
    def elli(self, mat: Mat4, w: float, h: float, col: int) -> None: ...
    def ellib(self, mat: Mat4, w: float, h: float, col: int) -> None: ...
    def sprite(
        self,
        pos: Vec3,
        img: Image | Tilemap,
        uvs: tuple[
            tuple[float, float],
            tuple[float, float],
            tuple[float, float],
            tuple[float, float],
        ],
        w: float,
        h: float,
        colkey: int | None = None,
        angle: float = 0.0,
    ) -> None: ...
    def plane(
        self,
        mat: Mat4,
        img: Image | Tilemap,
        uvs: tuple[
            tuple[float, float],
            tuple[float, float],
            tuple[float, float],
            tuple[float, float],
        ],
        w: float,
        h: float,
        colkey: int | None = None,
    ) -> None: ...
    def mesh(self, mat: Mat4, mesh: Mesh) -> None: ...

    # Lifecycle hooks
    def on_update(self) -> None: ...
    def on_draw(self) -> None: ...
    def on_collide(self, other: Node, contact: Contact | None) -> None: ...
    def on_destroy(self) -> None: ...

# Scene class
class Scene(Node):
    clear_color: int | None       # None skips clear; int fills screen + depth buffer

    def __init__(self) -> None: ...
    def update(self) -> None: ...
    def draw(
        self,
        x: int,
        y: int,
        w: int,
        h: int,
        camera: Camera,
        screen: Image | None = None,
    ) -> None: ...
