from typing import Iterator, overload

from pyxel import Image, Tilemap


# Vec3 class
class Vec3:
    x: float
    y: float
    z: float

    ZERO: Vec3
    ONE: Vec3
    RIGHT: Vec3
    LEFT: Vec3
    UP: Vec3
    DOWN: Vec3
    FORWARD: Vec3
    BACK: Vec3

    def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0) -> None: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __getitem__(self, key: int) -> float: ...
    def __iter__(self) -> Iterator[float]: ...
    def __len__(self) -> int: ...
    def __add__(self, other: Vec3) -> Vec3: ...
    def __sub__(self, other: Vec3) -> Vec3: ...
    def __mul__(self, scalar: float) -> Vec3: ...
    def __rmul__(self, scalar: float) -> Vec3: ...
    def __truediv__(self, scalar: float) -> Vec3: ...
    def __neg__(self) -> Vec3: ...
    def dot(self, other: Vec3) -> float: ...
    def cross(self, other: Vec3) -> Vec3: ...
    def length(self) -> float: ...
    def length_squared(self) -> float: ...
    def distance_to(self, other: Vec3) -> float: ...
    def distance_squared_to(self, other: Vec3) -> float: ...
    def angle_to(self, other: Vec3) -> float: ...
    def normalize(self) -> Vec3: ...
    def clamp_length(self, max_length: float) -> Vec3: ...
    def min(self, other: Vec3) -> Vec3: ...
    def max(self, other: Vec3) -> Vec3: ...
    def lerp(self, other: Vec3, t: float) -> Vec3: ...
    def slerp(self, other: Vec3, t: float) -> Vec3: ...
    def reflect(self, normal: Vec3) -> Vec3: ...
    def project(self, other: Vec3) -> Vec3: ...
    def to_local(self, mat: Mat4) -> Vec3: ...
    def to_world(self, mat: Mat4) -> Vec3: ...
    def to_local_dir(self, mat: Mat4) -> Vec3: ...
    def to_world_dir(self, mat: Mat4) -> Vec3: ...

# Mat4 class
class Mat4:
    IDENTITY: Mat4

    pos: Vec3
    rot: Vec3
    scale: Vec3

    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __getitem__(self, key: tuple[int, int]) -> float: ...
    @overload
    def __mul__(self, other: Mat4) -> Mat4: ...
    @overload
    def __mul__(self, other: Vec3) -> Vec3: ...
    @staticmethod
    def from_translation(pos: Vec3) -> Mat4: ...
    @staticmethod
    def from_rotation(rot: Vec3) -> Mat4: ...
    @staticmethod
    def from_quat(quat: Quat) -> Mat4: ...
    @staticmethod
    def from_scale(scale: Vec3) -> Mat4: ...
    @staticmethod
    def compose(pos: Vec3, rot: Vec3, scale: Vec3) -> Mat4: ...
    @staticmethod
    def look_at(eye: Vec3, target: Vec3, up: Vec3 = Vec3.UP) -> Mat4: ...
    def translate(self, v: Vec3) -> Mat4: ...
    def rotate(self, axis: Vec3, deg: float) -> Mat4: ...
    def rotate_x(self, deg: float) -> Mat4: ...
    def rotate_y(self, deg: float) -> Mat4: ...
    def rotate_z(self, deg: float) -> Mat4: ...
    def scale_by(self, v: Vec3) -> Mat4: ...
    def inverse(self) -> Mat4: ...
    def transpose(self) -> Mat4: ...
    def determinant(self) -> float: ...
    def to_local(self, mat: Mat4) -> Mat4: ...
    def to_world(self, mat: Mat4) -> Mat4: ...
    def to_local_dir(self, mat: Mat4) -> Mat4: ...
    def to_world_dir(self, mat: Mat4) -> Mat4: ...

# Quat class
class Quat:
    IDENTITY: Quat

    x: float
    y: float
    z: float
    w: float

    def __init__(
        self,
        x: float = 0.0,
        y: float = 0.0,
        z: float = 0.0,
        w: float = 1.0,
    ) -> None: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __getitem__(self, key: int) -> float: ...
    def __iter__(self) -> Iterator[float]: ...
    def __len__(self) -> int: ...
    def __neg__(self) -> Quat: ...
    @overload
    def __mul__(self, other: Quat) -> Quat: ...
    @overload
    def __mul__(self, other: Vec3) -> Vec3: ...
    @staticmethod
    def from_axis_angle(axis: Vec3, deg: float) -> Quat: ...
    @staticmethod
    def from_euler(rot: Vec3) -> Quat: ...
    @staticmethod
    def from_two_vectors(a: Vec3, b: Vec3) -> Quat: ...
    @staticmethod
    def from_matrix(mat: Mat4) -> Quat: ...
    def conjugate(self) -> Quat: ...
    def inverse(self) -> Quat: ...
    def normalize(self) -> Quat: ...
    def length(self) -> float: ...
    def length_squared(self) -> float: ...
    def dot(self, other: Quat) -> float: ...
    def angle_to(self, other: Quat) -> float: ...
    def to_matrix(self) -> Mat4: ...
    def to_euler(self) -> Vec3: ...
    def to_axis_angle(self) -> tuple[Vec3, float]: ...
    def slerp(self, other: Quat, t: float) -> Quat: ...

# Camera class
class Camera:
    transform: Mat4
    fov: float
    near: float
    far: float
    ortho_size: float | None

    def __init__(self) -> None: ...

# Ramp class
class Ramp:
    def __init__(self) -> None: ...
    def __getitem__(self, key: tuple[int, int]) -> int: ...
    def __setitem__(self, key: tuple[int, int], value: int) -> None: ...
    def build(self) -> None: ...
    def to_list(self) -> list[list[int]]: ...
    def from_list(self, table: list[list[int]]) -> None: ...

# Light class
class Light:
    ambient: float
    direction: Vec3
    intensity: float

    def __init__(self) -> None: ...

# Mesh class
class Mesh:
    def __init__(self, filename: str) -> None: ...
    def create_node(self) -> Node: ...

# Node class
class Node:
    transform: Mat4
    visible: bool

    @property
    def parent(self) -> Node | None: ...
    @property
    def children(self) -> tuple[Node, ...]: ...

    def add_child(self, node: Node) -> None: ...
    def remove_child(self, node: Node) -> None: ...

# Scene class
class Scene:
    def __init__(self) -> None: ...
    def clear(self, col: int | None = None) -> None: ...
    def render(
        self,
        x: float,
        y: float,
        w: float,
        h: float,
        camera: Camera,
    ) -> None: ...
    def line(self, pos1: Vec3, pos2: Vec3, col: int) -> None: ...
    def circ(self, pos: Vec3, r: float, col: int) -> None: ...
    def circb(self, pos: Vec3, r: float, col: int) -> None: ...
    def rect(self, mat: Mat4, w: float, h: float, col: int) -> None: ...
    def rectb(self, mat: Mat4, w: float, h: float, col: int) -> None: ...
    def elli(self, mat: Mat4, w: float, h: float, col: int) -> None: ...
    def ellib(self, mat: Mat4, w: float, h: float, col: int) -> None: ...
    def sprite(
        self,
        pos: Vec3,
        img: Image | Tilemap,
        uvs: tuple[
            tuple[float, float],
            tuple[float, float],
            tuple[float, float],
            tuple[float, float],
        ],
        w: float,
        h: float,
        colkey: int | None = None,
        angle: float = 0.0,
    ) -> None: ...
    def plane(
        self,
        mat: Mat4,
        img: Image | Tilemap,
        uvs: tuple[
            tuple[float, float],
            tuple[float, float],
            tuple[float, float],
            tuple[float, float],
        ],
        w: float,
        h: float,
        colkey: int | None = None,
    ) -> None: ...
    def model(self, mat: Mat4, node: Node) -> None: ...
