from __future__ import annotations

from typing import Iterator, overload

from pyxel import Font, Image

# Vec3 class
class Vec3:
    ZERO: Vec3
    ONE: Vec3
    RIGHT: Vec3
    LEFT: Vec3
    UP: Vec3
    DOWN: Vec3
    FORWARD: Vec3
    BACK: Vec3

    x: float
    y: float
    z: float

    def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0) -> None: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __getitem__(self, key: int) -> float: ...
    def __iter__(self) -> Iterator[float]: ...
    def __len__(self) -> int: ...
    def __add__(self, other: Vec3) -> Vec3: ...
    def __sub__(self, other: Vec3) -> Vec3: ...
    def __mul__(self, scalar: float) -> Vec3: ...
    def __rmul__(self, scalar: float) -> Vec3: ...
    def __truediv__(self, scalar: float) -> Vec3: ...
    def __neg__(self) -> Vec3: ...
    def dot(self, other: Vec3) -> float: ...
    def cross(self, other: Vec3) -> Vec3: ...
    def length(self) -> float: ...
    def length_squared(self) -> float: ...
    def distance_to(self, other: Vec3) -> float: ...
    def distance_squared_to(self, other: Vec3) -> float: ...
    def angle_to(self, other: Vec3) -> float: ...
    def normalize(self) -> Vec3: ...
    def clamp_length(self, max_length: float) -> Vec3: ...
    def min(self, other: Vec3) -> Vec3: ...
    def max(self, other: Vec3) -> Vec3: ...
    def lerp(self, other: Vec3, t: float) -> Vec3: ...
    def slerp(self, other: Vec3, t: float) -> Vec3: ...
    def reflect(self, normal: Vec3) -> Vec3: ...
    def project(self, other: Vec3) -> Vec3: ...
    def to_local(self, mat: Mat4) -> Vec3: ...
    def to_world(self, mat: Mat4) -> Vec3: ...
    def to_local_dir(self, mat: Mat4) -> Vec3: ...
    def to_world_dir(self, mat: Mat4) -> Vec3: ...

# Mat4 class
class Mat4:
    IDENTITY: Mat4

    pos: Vec3
    rot: Quat
    scale: Vec3

    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __getitem__(self, key: tuple[int, int]) -> float: ...
    @overload
    def __mul__(self, other: Mat4) -> Mat4: ...
    @overload
    def __mul__(self, other: Vec3) -> Vec3: ...
    @staticmethod
    def from_translation(pos: Vec3) -> Mat4: ...
    @staticmethod
    def from_euler(euler: Vec3) -> Mat4: ...
    @staticmethod
    def from_quat(rot: Quat) -> Mat4: ...
    @staticmethod
    def from_scale(scale: Vec3) -> Mat4: ...
    @staticmethod
    def from_axis_angle(axis: Vec3, deg: float) -> Mat4: ...
    @staticmethod
    def compose(pos: Vec3, rot: Quat, scale: Vec3) -> Mat4: ...
    @staticmethod
    def look_at(eye: Vec3, target: Vec3, up: Vec3 = Vec3.UP) -> Mat4: ...
    def translate(self, v: Vec3) -> Mat4: ...
    def rotate(self, axis: Vec3, deg: float) -> Mat4: ...
    def rotate_x(self, deg: float) -> Mat4: ...
    def rotate_y(self, deg: float) -> Mat4: ...
    def rotate_z(self, deg: float) -> Mat4: ...
    def scale_by(self, v: Vec3) -> Mat4: ...
    def inverse(self) -> Mat4: ...
    def transpose(self) -> Mat4: ...
    def determinant(self) -> float: ...
    def to_local(self, mat: Mat4) -> Mat4: ...
    def to_world(self, mat: Mat4) -> Mat4: ...
    def to_local_dir(self, mat: Mat4) -> Mat4: ...
    def to_world_dir(self, mat: Mat4) -> Mat4: ...

# Quat class
class Quat:
    IDENTITY: Quat

    x: float
    y: float
    z: float
    w: float

    def __init__(
        self,
        x: float = 0.0,
        y: float = 0.0,
        z: float = 0.0,
        w: float = 1.0,
    ) -> None: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __getitem__(self, key: int) -> float: ...
    def __iter__(self) -> Iterator[float]: ...
    def __len__(self) -> int: ...
    @overload
    def __mul__(self, other: Quat) -> Quat: ...
    @overload
    def __mul__(self, other: Vec3) -> Vec3: ...
    def __neg__(self) -> Quat: ...
    @staticmethod
    def from_axis_angle(axis: Vec3, deg: float) -> Quat: ...
    @staticmethod
    def from_euler(rot: Vec3) -> Quat: ...
    @staticmethod
    def from_two_vectors(a: Vec3, b: Vec3) -> Quat: ...
    @staticmethod
    def from_matrix(mat: Mat4) -> Quat: ...
    @staticmethod
    def from_direction(forward: Vec3, up: Vec3 = Vec3.UP) -> Quat: ...
    def conjugate(self) -> Quat: ...
    def inverse(self) -> Quat: ...
    def normalize(self) -> Quat: ...
    def length(self) -> float: ...
    def length_squared(self) -> float: ...
    def dot(self, other: Quat) -> float: ...
    def angle_to(self, other: Quat) -> float: ...
    def to_matrix(self) -> Mat4: ...
    def to_euler(self) -> Vec3: ...
    def to_axis_angle(self) -> tuple[Vec3, float]: ...
    def slerp(self, other: Quat, t: float) -> Quat: ...

# Camera class
class Camera:
    transform: Mat4
    fov: float
    near: float
    far: float
    ortho_size: float | None

    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...

# Shading class — palette × level color lookup table with scene-wide light direction.
class Shading:
    direction: Vec3

    def __init__(self, colors: list[int]) -> None: ...
    def __repr__(self) -> str: ...
    def __getitem__(self, key: tuple[int, int]) -> tuple[int, int]: ...
    def __setitem__(self, key: tuple[int, int], value: tuple[int, int]) -> None: ...
    def build(self, colors: list[int]) -> None: ...

# Geometry class — static vertex-data asset shareable across Node draws and Mesh parts.
class Geometry:
    PRIM_POINTS: int
    PRIM_LINES: int
    PRIM_TRIANGLES: int

    CULL_NONE: int
    CULL_BACK: int
    CULL_FRONT: int

    positions: list[float]
    normals: list[float] | None
    uvs: list[float] | None
    indices: list[int] | None
    prim: int
    cull: int

    def __init__(
        self,
        positions: list[float] | None = None,
        normals: list[float] | None = None,
        uvs: list[float] | None = None,
        indices: list[int] | None = None,
        prim: int = PRIM_TRIANGLES,
        cull: int = CULL_BACK,
    ) -> None: ...
    def __repr__(self) -> str: ...
    def compute_normals(self) -> None: ...

# Mesh class — hierarchical 3D model asset (parallel arrays of geometries / transforms / parents).
class Mesh:
    geometries: list[Geometry | None]  # None = pure group (transform-only)
    transforms: list[Mat4]
    parents: list[int]  # -1 = root; parents[i] < i invariant
    col_img: int | Image  # int = flat color, Image = texture for all parts
    colkey: int | None  # transparent color when col_img is Image

    def __init__(
        self,
        geometries: list[Geometry | None] | None = None,
        transforms: list[Mat4] | None = None,
        parents: list[int] | None = None,
        col_img: int | Image = 7,
        colkey: int | None = None,
    ) -> None: ...
    def __repr__(self) -> str: ...
    def descendants(self, i: int) -> list[int]: ...

# Collider class — unified shape + behavior flags + physical coefficients + motion state.
class Collider:
    size: Vec3
    radius: float
    mesh: Mesh | None
    trigger: bool
    rolls: bool
    mass: float
    restitution: float
    friction: float
    velocity: Vec3
    angular_velocity: Vec3

    def __init__(
        self,
        size: Vec3 = Vec3.ZERO,
        radius: float = 0.0,
        mesh: Mesh | None = None,
        trigger: bool = False,
        rolls: bool = False,
        mass: float = 1.0,
        restitution: float = 0.0,
        friction: float = 0.5,
        velocity: Vec3 = Vec3.ZERO,
        angular_velocity: Vec3 = Vec3.ZERO,
    ) -> None: ...
    def __repr__(self) -> str: ...

# Contact class — collision payload for on_collide (geometry + engine-resolved motion deltas).
class Contact:
    point: Vec3
    normal: Vec3
    depth: float
    delta_rotation: Quat
    delta_velocity: Vec3
    delta_angular_velocity: Vec3

    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...

# RaycastHit class — payload returned by Node.raycast / raycast_all.
class RaycastHit:
    node: Node
    point: Vec3
    normal: Vec3
    distance: float

    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...

# Node class
class Node:
    # Data attributes
    name: str
    transform: Mat4
    active: bool  # parent-dominant; False halts update + collision
    visible: bool  # parent-dominant; False halts drawing
    shading: Shading | None  # None inherits from the closest non-None ancestor
    collider: Collider | None
    tags: list[str]

    # Properties
    @property
    def parent(self) -> Node | None: ...
    @property
    def children(self) -> tuple[Node, ...]: ...
    @property
    def destroyed(self) -> bool: ...
    @property
    def forward(self) -> Vec3: ...
    @property
    def right(self) -> Vec3: ...
    @property
    def up(self) -> Vec3: ...

    # Constructor
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...

    # Hierarchy management
    @property
    def world_transform(self) -> Mat4: ...
    def find_by_name(self, name: str) -> list[Node]: ...
    def find_by_tags(self, tags: str | list[str]) -> list[Node]: ...
    def add_child(self, node: Node) -> None: ...
    def remove_child(self, node: Node) -> None: ...
    def destroy(self) -> None: ...

    # Lifecycle hooks
    def on_update(self) -> None: ...
    def on_draw(self) -> None: ...
    def on_collide(self, other: Node, contact: Contact) -> None: ...
    def on_destroy(self) -> None: ...

    # Per-draw state setters; called from on_draw, reset at each Node's on_draw entry.
    def dither(self, alpha: float) -> None: ...
    def depth_test(self, on: bool) -> None: ...
    def depth_write(self, on: bool) -> None: ...
    def shaded(self, on: bool) -> None: ...

    # Linework
    def pset(self, pos: Vec3, col: int) -> None: ...
    def line(self, p1: Vec3, p2: Vec3, col: int) -> None: ...

    # 2D polygons
    def tri(self, p1: Vec3, p2: Vec3, p3: Vec3, col: int) -> None: ...
    def trib(self, p1: Vec3, p2: Vec3, p3: Vec3, col: int) -> None: ...
    def rect(self, mat: Mat4, w: float, h: float, col: int) -> None: ...
    def rectb(self, mat: Mat4, w: float, h: float, col: int) -> None: ...

    # 2D curves
    def circ(self, pos: Vec3, r: float, col: int) -> None: ...
    def circb(self, pos: Vec3, r: float, col: int) -> None: ...
    def elli(self, mat: Mat4, w: float, h: float, col: int) -> None: ...
    def ellib(self, mat: Mat4, w: float, h: float, col: int) -> None: ...

    # 3D solids
    def box(
        self,
        mat: Mat4,
        size: Vec3,
        col_img: int | Image = 7,
        *,
        colkey: int | None = None,
    ) -> None: ...
    def boxb(self, mat: Mat4, size: Vec3, col: int) -> None: ...
    def sphere(
        self,
        pos: Vec3,
        r: float,
        col_img: int | Image = 7,
        *,
        colkey: int | None = None,
    ) -> None: ...
    def sphereb(self, pos: Vec3, r: float, col: int) -> None: ...

    # Textured quads
    def plane(
        self,
        mat: Mat4,
        img: Image,
        uvs: tuple[
            tuple[float, float],
            tuple[float, float],
            tuple[float, float],
            tuple[float, float],
        ],
        w: float,
        h: float,
        *,
        colkey: int | None = None,
    ) -> None: ...
    def sprite(
        self,
        pos: Vec3,
        img: Image,
        uvs: tuple[
            tuple[float, float],
            tuple[float, float],
            tuple[float, float],
            tuple[float, float],
        ],
        w: float,
        h: float,
        *,
        colkey: int | None = None,
        angle: float = 0.0,
    ) -> None: ...

    # Asset-based
    def mesh(self, mat: Mat4, mesh_asset: Mesh) -> None: ...
    def prim(
        self,
        mat: Mat4,
        geom: Geometry,
        *,
        col_img: int | Image = 7,
        colkey: int | None = None,
    ) -> None: ...

    # Text
    def text(
        self,
        pos: Vec3,
        s: str,
        col: int,
        *,
        font: Font | None = None,
    ) -> None: ...

    # Frame-level pipeline
    def update(self) -> None: ...
    def draw(
        self,
        x: int,
        y: int,
        w: int,
        h: int,
        camera: Camera,
        clear_color: int | None = None,
        target: Image | None = None,
    ) -> None: ...

    # Spatial queries on this Node's subtree
    def raycast(
        self,
        origin: Vec3,
        direction: Vec3,
        max_distance: float | None = None,
        hit_triggers: bool = False,
        tags: str | list[str] | None = None,
    ) -> RaycastHit | None: ...
    def raycast_all(
        self,
        origin: Vec3,
        direction: Vec3,
        max_distance: float | None = None,
        hit_triggers: bool = False,
        tags: str | list[str] | None = None,
    ) -> list[RaycastHit]: ...
    def overlap_sphere(
        self,
        center: Vec3,
        radius: float,
        hit_triggers: bool = False,
        tags: str | list[str] | None = None,
    ) -> list[Node]: ...
    def overlap_box(
        self,
        transform: Mat4,
        size: Vec3,
        hit_triggers: bool = False,
        tags: str | list[str] | None = None,
    ) -> list[Node]: ...
